services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: postgres
      POSTGRES_DB: somedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./somesqlscript.sql:/docker-entrypoint-initdb.d/somesqlscript.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: somepassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: